[theme]
primaryColor="#1f77b4"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 7860

[browser]
gatherUsageStats = false
